import sys

with open("/Users/badenath/projects/local-llm-ui/app.py", "r") as f:
    content = f.read()

old_block = """        # 3. Code Generation (Selected Coder)
        status.write(f"🧠 **[GENIUS CODER]** {coder_model} is generating the unified diff...")
        system = f"You are the Genius Coder. \\nPROJECT MEMORY:\\n{memory}\\n\\nFILES:\\n{context}\\n\\nOutput ONLY valid JSON representing file edits. Do NOT rewrite the whole file. Use SEARCH and REPLACE blocks.\\nFormat: [{{'file': 'filename', 'search': 'exact old code to replace', 'replace': 'new code'}}] "
        coder_payload = {
            "model": coder_model,
            "messages": [{"role": "system", "content": system}, {"role": "user", "content": intent_prompt}],
            "stream": False, "options": {"temperature": 0.0}
        }
        
        coder_res = requests.post(f"{OLLAMA_URL}/api/chat", json=coder_payload)
        json_edits = coder_res.json().get("message", {}).get("content", "")
        
        if "```json" in json_edits: json_edits = json_edits.split("```json")[1].split("```")[0].strip()
        elif "```" in json_edits: json_edits = json_edits.split("```")[1].split("```")[0].strip()
        
        # 4. Apply, Verify, & Consolidate Memory
        try:
            import subprocess
            edits = json.loads(json_edits)
            for edit in edits:
                with open(edit["file"], "r") as f:
                    old_code = f.read()
                
                if edit["search"] not in old_code:
                    with open("PROJECT_MIND.md", "a") as f:
                        f.write(f"\\n- **Intent:** {intent_prompt}\\n  - **Files Edited:** {edit['file']}\\n  - **Status:** [INVALID] Search Block Hallucination\\n")
                    raise Exception(f"Coder hallucinated the search block for {edit['file']}. The exact text was not found in the file.")
                    
                new_code = old_code.replace(edit["search"], edit["replace"])
                with open(edit["file"], "w") as f:
                    f.write(new_code)
                
                # [VERIFICATION NODE]
                if edit["file"].endswith(".py"):
                    status.write(f"🔬 **[VERIFY]** Compiling {edit['file']} to check for syntax errors...")
                    check = subprocess.run(["python3", "-m", "py_compile", edit["file"]], capture_output=True, text=True)
                    if check.returncode != 0:
                        # Log to memory as INVALID
                        with open("PROJECT_MIND.md", "a") as f:
                            f.write(f"\\n- **Intent:** {intent_prompt}\\n  - **Files Edited:** {edit['file']}\\n  - **Status:** [INVALID] Syntax Error\\n")
                        raise Exception(f"Syntax Error generated by Coder:\\n{check.stderr}")
            
            status.write("🌙 **[NIDRA]** Consolidating edits into Pramana (Proven Truth) memory graph...")
            with open("PROJECT_MIND.md", "a") as f:
                f.write(f"\\n- **Intent:** {intent_prompt}\\n  - **Files Edited:** {', '.join(files)}\\n  - **Status:** [PRAMANA] Settled\\n")
            
            st.success("🎉 Edit applied successfully and Memory Graph updated!")
            with st.expander("View Memory Graph (PROJECT_MIND.md)"):
                with open("PROJECT_MIND.md", "r") as f: st.markdown(f.read())
            
            import time
            time.sleep(1)
            st.rerun() # Refresh the UI to update the Active Memory Monitor!
        except Exception as e:
            st.error(f"Failed to apply edits. Did the coder output valid JSON? Error: {e}")"""

new_block = """        # 3. Code Generation (Selected Coder) with Self-Healing Loop
        system = f"You are the Genius Coder. \\nPROJECT MEMORY:\\n{memory}\\n\\nFILES:\\n{context}\\n\\nOutput ONLY valid JSON representing file edits. Do NOT rewrite the whole file. Use SEARCH and REPLACE blocks.\\nFormat: [{{'file': 'filename', 'search': 'exact old code to replace', 'replace': 'new code'}}] "
        messages = [{"role": "system", "content": system}, {"role": "user", "content": intent_prompt}]
        
        max_retries = 3
        attempt = 0
        success = False
        
        while attempt < max_retries and not success:
            attempt += 1
            if attempt == 1:
                status.write(f"🧠 **[GENIUS CODER]** {coder_model} is generating the unified diff...")
            else:
                status.write(f"⚠️ **[SELF-HEALING]** Attempt {attempt}: Feeding error back to Coder...")
                
            coder_payload = {
                "model": coder_model,
                "messages": messages,
                "stream": False, "options": {"temperature": 0.0}
            }
            
            coder_res = requests.post(f"{OLLAMA_URL}/api/chat", json=coder_payload)
            raw_response = coder_res.json().get("message", {}).get("content", "")
            messages.append({"role": "assistant", "content": raw_response}) # Add to history
            
            json_edits = raw_response
            if "```json" in json_edits: json_edits = json_edits.split("```json")[1].split("```")[0].strip()
            elif "```" in json_edits: json_edits = json_edits.split("```")[1].split("```")[0].strip()
            
            # 4. Apply, Verify, & Consolidate Memory
            try:
                import subprocess
                edits = json.loads(json_edits)
                for edit in edits:
                    with open(edit["file"], "r") as f:
                        old_code = f.read()
                    
                    if edit["search"] not in old_code:
                        with open("PROJECT_MIND.md", "a") as f:
                            f.write(f"\\n- **Intent:** {intent_prompt}\\n  - **Files Edited:** {edit['file']}\\n  - **Status:** [INVALID] Search Block Hallucination\\n")
                        raise Exception(f"Coder hallucinated the search block for {edit['file']}. The exact text was not found in the file.")
                        
                    new_code = old_code.replace(edit["search"], edit["replace"])
                    with open(edit["file"], "w") as f:
                        f.write(new_code)
                    
                    # [VERIFICATION NODE]
                    if edit["file"].endswith(".py"):
                        status.write(f"🔬 **[VERIFY]** Compiling {edit['file']} to check for syntax errors...")
                        check = subprocess.run(["python3", "-m", "py_compile", edit["file"]], capture_output=True, text=True)
                        if check.returncode != 0:
                            # Log to memory as INVALID
                            with open("PROJECT_MIND.md", "a") as f:
                                f.write(f"\\n- **Intent:** {intent_prompt}\\n  - **Files Edited:** {edit['file']}\\n  - **Status:** [INVALID] Syntax Error\\n")
                            raise Exception(f"Syntax Error generated by Coder:\\n{check.stderr}")
                
                status.write("🌙 **[NIDRA]** Consolidating edits into Pramana (Proven Truth) memory graph...")
                with open("PROJECT_MIND.md", "a") as f:
                    f.write(f"\\n- **Intent:** {intent_prompt}\\n  - **Files Edited:** {', '.join(files)}\\n  - **Status:** [PRAMANA] Settled\\n")
                
                st.success("🎉 Edit applied successfully and Memory Graph updated!")
                with st.expander("View Memory Graph (PROJECT_MIND.md)"):
                    with open("PROJECT_MIND.md", "r") as f: st.markdown(f.read())
                
                success = True
                import time
                time.sleep(1)
                st.rerun() # Refresh the UI
                
            except Exception as e:
                st.error(f"Attempt {attempt} failed: {e}")
                messages.append({"role": "user", "content": f"Your previous code failed with this error:\\n{e}\\nPlease analyze the error, fix the search block or syntax, and output the correct JSON."})
                
        if not success:
            st.error("Failed to apply edits after maximum self-healing retries. Please check the logs.")"""

if old_block in content:
    content = content.replace(old_block, new_block)
    with open("/Users/badenath/projects/local-llm-ui/app.py", "w") as f:
        f.write(content)
    print("Patch applied successfully.")
else:
    print("Old block not found.")
